server:
  port: '8082'


spring:
  profiles:
    active: qa

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Hallo jungs

---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Hallo jungs

  ---

  spring:
    profiles: prod
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/dcbapp-prod
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  welcome:
    message: Hallo jungs
